version: '3.2'

networks:
  custom_network:
    driver: bridge

services:

  db:
    build:
      context: postgres
    restart: always
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpassword
    ports:
      - "5433:5432"
    networks:
      - custom_network

  backend:
      build: ./wheather-backend
      command: bash -c "chmod +x /backend/init.sh && /backend/init.sh"
      container_name: backend
      ports:
        - "8000:8000"
      depends_on:
        - db
      networks:
        - custom_network

  frounted:
    build:
      context: ./wheather-frounted
    container_name: frounted
    command: bash -c "npm install && npm start"
    restart: always
    ports:
      - "8080:8080"
    networks:
        - custom_network
